In [520]:
from sklearn.datasets import load_iris

In [522]:
from sklearn.model_selection import train_test_split

In [524]:
X,y = load_iris(return_X_y=True)

In [526]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [527]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [528]:
from sklearn.naive_bayes import GaussianNB

In [531]:
gnb = GaussianNB()

In [533]:
gnb.fit(X_train,y_train)

GaussianNB()

In [534]:
y_pred = gnb.predict(X_test)

In [536]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [537]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))


1.0
[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



# assignment -1 

In [539]:
import seaborn as sns 

In [540]:
df = sns.load_dataset('tips')

In [547]:
df 

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [549]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [551]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [552]:
df = df.drop(columns=['size'])

In [555]:
df

total_bill   tip     sex smoker   day    time
0         16.99  1.01  Female     No   Sun  Dinner
1         10.34  1.66    Male     No   Sun  Dinner
2         21.01  3.50    Male     No   Sun  Dinner
3         23.68  3.31    Male     No   Sun  Dinner
4         24.59  3.61  Female     No   Sun  Dinner
..          ...   ...     ...    ...   ...     ...
239       29.03  5.92    Male     No   Sat  Dinner
240       27.18  2.00  Female    Yes   Sat  Dinner
241       22.67  2.00    Male    Yes   Sat  Dinner
242       17.82  1.75    Male     No   Sat  Dinner
243       18.78  3.00  Female     No  Thur  Dinner

[244 rows x 6 columns]

## feature engineering  

In [558]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

## first, encode the target feature 

In [561]:
df

total_bill   tip     sex smoker   day    time
0         16.99  1.01  Female     No   Sun  Dinner
1         10.34  1.66    Male     No   Sun  Dinner
2         21.01  3.50    Male     No   Sun  Dinner
3         23.68  3.31    Male     No   Sun  Dinner
4         24.59  3.61  Female     No   Sun  Dinner
..          ...   ...     ...    ...   ...     ...
239       29.03  5.92    Male     No   Sat  Dinner
240       27.18  2.00  Female    Yes   Sat  Dinner
241       22.67  2.00    Male    Yes   Sat  Dinner
242       17.82  1.75    Male     No   Sat  Dinner
243       18.78  3.00  Female     No  Thur  Dinner

[244 rows x 6 columns]

In [562]:
from sklearn.preprocessing import LabelEncoder

In [565]:
label = LabelEncoder()

In [566]:
df['time'] = label.fit_transform(df['time'])

In [569]:
df['time'].value_counts()

time
0    176
1     68
Name: count, dtype: int64

In [570]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    int64   
dtypes: category(3), float64(2), int64(1)
memory usage: 7.0 KB


In [571]:
X = df.drop(columns=df[['time']])
y = df['time']

In [575]:
X

total_bill   tip     sex smoker   day
0         16.99  1.01  Female     No   Sun
1         10.34  1.66    Male     No   Sun
2         21.01  3.50    Male     No   Sun
3         23.68  3.31    Male     No   Sun
4         24.59  3.61  Female     No   Sun
..          ...   ...     ...    ...   ...
239       29.03  5.92    Male     No   Sat
240       27.18  2.00  Female    Yes   Sat
241       22.67  2.00    Male    Yes   Sat
242       17.82  1.75    Male     No   Sat
243       18.78  3.00  Female     No  Thur

[244 rows x 5 columns]

In [576]:
y

0      0
1      0
2      0
3      0
4      0
      ..
239    0
240    0
241    0
242    0
243    0
Name: time, Length: 244, dtype: int64

## TRAIN TEST SPLIT 

In [580]:
from sklearn.model_selection import train_test_split

In [582]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=10)

In [584]:
X_train

total_bill   tip     sex smoker   day
39        31.27  5.00    Male     No   Sat
87        18.28  4.00    Male     No  Thur
169       10.63  2.00  Female    Yes   Sat
232       11.61  3.39    Male     No   Sat
144       16.43  2.30  Female     No  Thur
..          ...   ...     ...    ...   ...
64        17.59  2.64    Male     No   Sat
15        21.58  3.92    Male     No   Sun
228       13.28  2.72    Male     No   Sat
125       29.80  4.20  Female     No  Thur
9         14.78  3.23    Male     No   Sun

[170 rows x 5 columns]

In [586]:
labelgender = LabelEncoder()
labelsmoker = LabelEncoder()

In [588]:
X_train['sex'] = labelgender.fit_transform(X_train['sex'])
X_train['smoker'] = labelsmoker.fit_transform(X_train['smoker'])

In [590]:
X_test['sex'] = labelgender.transform(X_test['sex'])
X_test['smoker'] = labelsmoker.transform(X_test['smoker'])

In [592]:
X_train

total_bill   tip  sex  smoker   day
39        31.27  5.00    1       0   Sat
87        18.28  4.00    1       0  Thur
169       10.63  2.00    0       1   Sat
232       11.61  3.39    1       0   Sat
144       16.43  2.30    0       0  Thur
..          ...   ...  ...     ...   ...
64        17.59  2.64    1       0   Sat
15        21.58  3.92    1       0   Sun
228       13.28  2.72    1       0   Sat
125       29.80  4.20    0       0  Thur
9         14.78  3.23    1       0   Sun

[170 rows x 5 columns]

In [594]:
X_test

total_bill   tip  sex  smoker   day
162       16.21  2.00    0       0   Sun
60        20.29  3.21    1       1   Sat
61        13.81  2.00    1       1   Sat
63        18.29  3.76    1       1   Sat
69        15.01  2.09    1       1   Sat
..          ...   ...  ...     ...   ...
142       41.19  5.00    1       0  Thur
32        15.06  3.00    0       0   Sat
242       17.82  1.75    1       0   Sat
7         26.88  3.12    1       0   Sun
243       18.78  3.00    0       0  Thur

[74 rows x 5 columns]

In [596]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [598]:
ct = ColumnTransformer(transformers = [('onehot',OneHotEncoder(drop='first'),[4])],remainder='passthrough')

In [600]:
import sys
import numpy 
numpy.set_printoptions(threshold=sys.maxsize)
X_train = ct.fit_transform(X_train)
X_test = ct.transform(X_test)

In [602]:
X_train

array([[ 1.  ,  0.  ,  0.  , 31.27,  5.  ,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 18.28,  4.  ,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 10.63,  2.  ,  0.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  , 11.61,  3.39,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 16.43,  2.3 ,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 24.27,  2.03,  1.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  , 15.36,  1.64,  1.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  , 32.83,  1.17,  1.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  , 22.76,  3.  ,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 17.81,  2.34,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 12.48,  2.52,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 17.89,  2.  ,  1.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  , 26.86,  3.14,  0.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  , 10.77,  1.47,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 15.69,  3.  ,  1.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  , 10.59,  1.61,  0.  ,  1.  ],
       [ 0.  ,  1.  ,  0.  , 18.15,  3.5 ,  0.  ,  1.  ],
       [ 1.  ,

## naive bayes 


In [605]:
from sklearn.naive_bayes import GaussianNB

In [607]:
gnb = GaussianNB()
gnb.fit(X_train,y_train)

GaussianNB()

In [609]:
y_pred = gnb.predict(X_test)

In [611]:
y_pred

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1])

In [613]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [615]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))


0.9594594594594594
[[51  3]
 [ 0 20]]
              precision    recall  f1-score   support

           0       1.00      0.94      0.97        54
           1       0.87      1.00      0.93        20

    accuracy                           0.96        74
   macro avg       0.93      0.97      0.95        74
weighted avg       0.96      0.96      0.96        74

