In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt 
import numpy as np 
%matplotlib inline 


In [4]:
from sklearn.datasets import make_classification

X , y = make_classification(
    n_samples = 1000, # no of samples  
    n_features = 3,  # no of features 
    n_redundant = 1,
    n_classes = 2 , # it can binary or maultiple class 
    random_state = 999
)

In [6]:
X

array([[-0.33504974,  0.02852654,  1.16193084],
       [-1.37746253, -0.4058213 ,  0.44359618],
       [-1.04520026, -0.72334759, -3.10470423],
       ...,
       [-0.75602574, -0.51816111, -2.20382324],
       [ 0.56066316, -0.07335845, -2.15660348],
       [-1.87521902, -1.11380394, -4.04620773]])

In [8]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [10]:
X_train

array([[-1.06405731, -0.22324023,  1.09027381],
       [-1.0061151 , -0.22717707,  0.89758841],
       [-1.23920161, -0.39578173,  0.14480054],
       ...,
       [-0.62173685, -0.12586518,  0.67496125],
       [ 1.63275027,  0.7152537 ,  1.41447324],
       [ 0.21192241, -0.11262328, -1.51843229]])

In [12]:
y_train

array([0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,

In [20]:
from sklearn.neighbors import KNeighborsClassifier

### parameters 

#### p=1 manhattan or p=2 euclidian 
#### n_neighbour denotes k value 
#### algorith : kdtree , balltree, brute, auto (data set anussacrich ethengilum onn kodukum auto koduthal )

In [28]:
classify = KNeighborsClassifier(n_neighbors=5,algorithm='auto')
classify.fit(X_train,y_train)

KNeighborsClassifier()

In [30]:
y_pred = classify.predict(X_test)


In [32]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [34]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.906060606060606
[[158  11]
 [ 20 141]]
              precision    recall  f1-score   support

           0       0.89      0.93      0.91       169
           1       0.93      0.88      0.90       161

    accuracy                           0.91       330
   macro avg       0.91      0.91      0.91       330
weighted avg       0.91      0.91      0.91       330



### task


In [37]:
model = KNeighborsClassifier()
k = [1,2,3,4,5,6,7,8,9,10]


In [39]:
params = dict(
    n_neighbors = k 
)

In [41]:
from sklearn.model_selection import StratifiedKFold
cv = StratifiedKFold()

In [43]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(estimator=model , param_grid = params , scoring='accuracy',cv=cv,n_jobs = -1)

In [45]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]},
             scoring='accuracy')

In [47]:
grid.fit(X_train,y_train)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]},
             scoring='accuracy')

In [51]:
grid.best_params_

{'n_neighbors': 9}

In [55]:
y_pred = grid.predict(X_test)

In [57]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9121212121212121
[[156  13]
 [ 16 145]]
              precision    recall  f1-score   support

           0       0.91      0.92      0.91       169
           1       0.92      0.90      0.91       161

    accuracy                           0.91       330
   macro avg       0.91      0.91      0.91       330
weighted avg       0.91      0.91      0.91       330

